import { QuickPreset, SamplePhoto } from "./types";

export const SAMPLE_PHOTOS: SamplePhoto[] = [
  {
    id: "watch",
    title: "Chronograph Watch",
    category: "Luxury & Accessories",
    description: "Wristwatch with dust specks on glass and busy wooden desk background.",
    url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Remove the background completely. Place this watch on a clean white surface with a soft natural contact shadow, and polish the glass surface.",
  },
  {
    id: "sneaker",
    title: "Urban Athletic Sneaker",
    category: "Footwear & Apparel",
    description: "Lifestyle sneaker with concrete texture background and subtle dust.",
    url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Remove the background completely and make it pure clean #FFFFFF white for e-commerce. Clean up dirt from the sole edges.",
  },
  {
    id: "perfume",
    title: "Glass Fragrance Bottle",
    category: "Cosmetics & Beauty",
    description: "Translucent bottle with distracting window reflections and room clutter.",
    url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Remove background. Place the perfume bottle on a sleek warm travertine stone plinth with soft diffused sunlight and gentle water ripple reflections.",
  },
  {
    id: "headphones",
    title: "Wireless Over-Ear Headphones",
    category: "Electronics",
    description: "Matte black headphones with fingerprints and distracting office desk background.",
    url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Clean all fingerprints and dust from the headphone earcups. Remove background and place on a minimal dark slate podium with subtle cyan rim lighting.",
  },
  {
    id: "ceramic-mug",
    title: "Artisanal Coffee Mug",
    category: "Home & Kitchen",
    description: "Ceramic cup with coffee stains and busy kitchen countertop background.",
    url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Clean up coffee smudges, remove the kitchen background, and place on a warm oak wood tabletop with soft morning window light.",
  },
  {
    id: "leather-bag",
    title: "Handcrafted Leather Tote",
    category: "Fashion & Bags",
    description: "Brown leather bag with uneven shadows and casual room background.",
    url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1000&auto=format&fit=crop&q=80",
    suggestedPrompt: "Isolate product with transparent background, fix lighting to evenly illuminate the leather grain, and remove background clutter.",
  },
];

export const QUICK_PRESETS: QuickPreset[] = [
  {
    id: "pure-white",
    label: "Pure White Studio",
    iconName: "SunMedium",
    category: "background",
    description: "100% white background (#FFFFFF) with gentle ground contact shadow. Meets Amazon & Shopify catalog standards.",
    prompt: "Remove background completely and replace with 100% pure clean white studio background (#FFFFFF). Add a subtle, realistic soft contact shadow under the product base.",
  },
  {
    id: "transparent",
    label: "Transparent Cutout",
    iconName: "Grid",
    category: "background",
    description: "Cleanly isolates the product subject with crisp, anti-aliased edges and no background.",
    prompt: "Isolate the product completely on a clean, empty transparent background. Ensure ultra-sharp, anti-aliased cutout edges around the entire product silhouette.",
  },
  {
    id: "deep-clean",
    label: "Clean Dust & Scratches",
    iconName: "Sparkles",
    category: "cleanup",
    description: "Removes dust specks, fingerprints, surface scratches, and glare while keeping product logos sharp.",
    prompt: "Carefully clean up the product surface: remove all dust specks, scratches, smudges, and harsh lens reflections. Keep all product logos, text, and original textures sharp and untouched.",
  },
  {
    id: "minimalist-pedestal",
    label: "Minimalist Stone Plinth",
    iconName: "Box",
    category: "staging",
    description: "Places the product on an elegant travertine or concrete geometric pedestal with soft studio light.",
    prompt: "Remove the background and place the product on a modern minimalist round travertine stone pedestal in an architectural studio setting with soft warm directional sunlight.",
  },
  {
    id: "organic-nature",
    label: "Botanical Sunlit Tabletop",
    iconName: "Leaf",
    category: "staging",
    description: "Warm organic setting with light oak wood and gentle tropical leaf shadow cast.",
    prompt: "Remove background and stage this product on a light natural oak wood surface. Add soft morning sunlight with gentle blurred shadows of green botanical leaves cast on the wall behind it.",
  },
  {
    id: "luxury-dark",
    label: "Dark Luxury Editorial",
    iconName: "Moon",
    category: "staging",
    description: "Matte charcoal slate and dramatic moody rim lighting for high-end luxury products.",
    prompt: "Place the product on a sleek matte dark charcoal slate surface with dramatic editorial rim lighting and subtle atmospheric reflections.",
  },
  {
    id: "softbox-lighting",
    label: "Studio Softbox Lighting",
    iconName: "Lamp",
    category: "lighting",
    description: "Balances highlights and fills harsh dark shadows with professional 3-point softbox studio lighting.",
    prompt: "Remove the background and relight the product using professional 3-point softbox photography lighting. Eliminate harsh dark shadows, bring out product colors, and place on a seamless light gray cyclorama backdrop.",
  },
];
